version: '3'
services:
  revanced-builder:
    container_name: revanced-builder
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./revanced/:/app/revanced-builder/revanced/
    extra_hosts:
      - "www.apkmirror.com:23.239.4.230"
      - "apkmirror.com:23.239.4.230"
    ports:
      - 8000:8000
